import { cifUs, cifVn } from '@coreui/icons/js/flag';
import {
  cilAccountLogout,
  cilApplicationsSettings,
  cilArrowCircleTop,
  cilArrowThickFromRight,
  cilCopy,
  cilExternalLink,
  cilFilter,
  cilFilterX,
  cilFlower,
  cilHistory,
  cilMenu,
  cilMinus,
  cilMoon,
  cilPlus,
  cilQrCode,
  cilSpeedometer,
  cilSun,
  cilTrash,
  cilX,
  cilArrowCircleLeft,
} from '@coreui/icons/js/free';

export const icons = Object.assign(
  {},
  {},
  {
    cilAccountLogout,
    cilApplicationsSettings,
    cilArrowCircleTop,
    cilArrowThickFromRight,
    cilCopy,
    cilExternalLink,
    cilFilter,
    cilFlower,
    cilHistory,
    cilMenu,
    cilMoon,
    cilQrCode,
    cilSpeedometer,
    cilSun,
    cilTrash,
    cilX,
    cilArrowCircleLeft,
    cilFilterX,
    cilMinus,
    cilPlus,
  },
  {
    cifVn,
    cifUs,
  }
);
