export enum BlockType {
    UNREGISTER = 'UNREGISTER',
    REGISTER = 'REGISTER',
    CLAIM = 'CLAIM',
    WITHDRAW ='WITHDRAW',
    OWNER_SHIP_EXTENSION = 'OWNER_SHIP_EXTENSION',
    UPDATE_WORKER = 'UPDATE_WORKER'
}