export enum EventType {
    UNREGISTER = 'UNREGISTER',
    REGISTER = 'REGISTER',
    CLAIM = 'CLAIM',
    WITHDRAW ='WITHDRAW',
    OWNERSHIP_EXTENSION = 'OWNERSHIP_EXTENSION',
    UPDATE_WORKER = 'UPDATE_WORKER'
}